Repository fnplus/footsteps-app, pull requests merged in 2020-03, with the labels that each got.

#46 Fixes #23: Contribution guidelines
  Guidelines.md
  images/clone.png
  images/congrats.gif
  images/fork.png
  images/git_cheat_sheet.jpg
  images/open_source.png
  images/pull_request.png
  images/welcome.png
Labels: beginner, gssoc20

#60 Fixed Type Error while loading User Public Page #50
  src/components/publicProfile.js
Labels: easy, gssoc20

#62 Learning path public profile #61
  src/components/publicProfile.js
  src/styles/user.module.css
Labels: gssoc20, medium

#78 Added the url validator function
  src/components/Login/signUpFlow.js
  src/components/Settings/settings.js
Labels: beginner, gssoc20

#84 SEO for publicProfile component
  src/components/publicProfile.js
Labels: easy, gssoc20

#90 Resolved Merging, Issue User Progress Bar #63
  package-lock.json
  package.json
  src/components/User/index.js
  src/components/User/userProgressBar.js
  src/styles/user.module.css
Labels: gssoc20, medium

#99 Fixed issue #56 (Design a new 404 Page)
  src/pages/404.js
Labels: beginner, gssoc20

#102 Added ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: beginner, gssoc20

#116 omission of row
  src/components/publicProfile.js
Labels: beginner, gssoc20
