Repository fnplus/footsteps-app, pull requests merged in 2020-04, with the labels that each got.

#124 fized hidden profile progress bar if completed, increased width to 100%
  src/components/User/userProgressBar.js
Labels: beginner, gssoc20

#130 Added Social Media colorful icons and organised mentors in tabular form.
  README.md
Labels: beginner, gssoc20

#134 Modified the landing page (#48)
  src/components/Landing/index.js
  src/components/Login/loginFlow.js
  src/images/FAQ.png
  src/images/LoginPageImg.png
  src/images/figuringOut.png
  src/styles/landing.module.css
  src/styles/login.module.css
Labels: gssoc20, hard

#137 migrating 'react-tag-input' dependency to 'react-tag-autocomplete'
  package-lock.json
  package.json
  src/apollo/client.js
  src/components/Create/addFootstep.js
  src/components/Create/addPath.js
  src/components/EditPath/editFootstep.js
  src/components/EditPath/editPath.js
  src/components/Landing/searchbar.js
  src/components/Layout/layout.js
  src/components/Layout/menu.js
  src/components/Layout/sideDrawer.js
  src/components/Login/signUpFlow.js
  src/components/Search/searchResult.js
  src/components/Settings/index.js
  src/components/Settings/settings.js
  src/components/User/follow.js
  src/components/User/learningPaths.js
  src/components/publicProfile.js
  src/firebase/config.js
  src/utils/typography.js
Labels: easy, gssoc20

#140 Mark as done icon added
  src/components/User/footstepsCard.js
  src/styles/footsteps.module.css
Labels: easy, gssoc20
